### ISSUE TITLE
example code

### ISSUE THREAD

**Issue by guoxiaolu** [WilCrofter/BuzzHash#1]
Brilliant job, I have just seen this interesting paper, and find the open source code. I have seen your code, but it seems there isn't an example code. Can you give an example code? Thank you very much.

**Comment by WilCrofter** [comment]
Thanks, @guoxiaolu. You are absolutely right, examples are needed. I pushed to github earlier than I might  have because a friend from NIA was interested. I've been preoccupied with another project (lame--I know :-D ) but that is stable, so an example is now my top priority.

Have you seen @dataplayer12's [Python implementation](https://github.com/dataplayer12/Fly-LSH) and his very nice [explanatory post at Medium](https://medium.com/@jaiyamsharma/efficient-nearest-neighbors-inspired-by-the-fruit-fly-brain-6ef8fed416ee)?

**Comment by dataplayer12** [comment]
Thanks @WilCrofter  for taking note. @guoxiaolu please see the jupyter notebook in my repo for quickly trying out the algorithm. Also, if you use an autoencoder (as I explain in my post on Medium), you can get even better performance.

**Comment by guoxiaolu** [comment]
Thank you very much, it is helpful. and @dataplayer12 code runs correctly, and helps me understanding.
